//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rosser.SatisfactoryExtractor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rosser.SatisfactoryExtractor.Resources.ErrorStrings", typeof(ErrorStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All of $1 must be specified.
        /// </summary>
        public static string FluentValidatorAll {
            get {
                return ResourceManager.GetString("FluentValidatorAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one of $1 must be specified.
        /// </summary>
        public static string FluentValidatorAny {
            get {
                return ResourceManager.GetString("FluentValidatorAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $1 must be an existing directory.
        /// </summary>
        public static string FluentValidatorDirectoryExists {
            get {
                return ResourceManager.GetString("FluentValidatorDirectoryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $1 must be an existing file.
        /// </summary>
        public static string FluentValidatorFileExists {
            get {
                return ResourceManager.GetString("FluentValidatorFileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $1 must not be an existing file or directory.
        /// </summary>
        public static string FluentValidatorFsDoesNotExist {
            get {
                return ResourceManager.GetString("FluentValidatorFsDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $1 are mutually exclusive.
        /// </summary>
        public static string FluentValidatorMutuallyExclusive {
            get {
                return ResourceManager.GetString("FluentValidatorMutuallyExclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None of $1 can be specified.
        /// </summary>
        public static string FluentValidatorNone {
            get {
                return ResourceManager.GetString("FluentValidatorNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $1 must match one of $2.
        /// </summary>
        public static string FluentValidatorOneOf {
            get {
                return ResourceManager.GetString("FluentValidatorOneOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $1 is required.
        /// </summary>
        public static string FluentValidatorRequired {
            get {
                return ResourceManager.GetString("FluentValidatorRequired", resourceCulture);
            }
        }
    }
}
